[package]
name = "aoc-24-day-6"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ratatui = "0.29.0"
aoc-visualisation = { git = "ssh://git@github.com/codersparks/aoc-rust-utils.git" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

