[package]
name = "aoc-24-day-6"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ratatui = {  version = "0.29.0"}
aoc-visualisation = { git = "ssh://git@github.com/codersparks/aoc-rust-utils.git" }

